# Generated by Django 4.2 on 2026-02-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('field', models.CharField(choices=[('data_science', 'Data Science'), ('web_dev', 'Web Development'), ('ai_ml', 'AI / ML'), ('cyber_security', 'Cyber Security'), ('cloud', 'Cloud Computing')], max_length=50)),
                ('description', models.TextField()),
                ('official_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='field_of_interest',
            field=models.CharField(blank=True, choices=[('data_science', 'Data Science'), ('web_dev', 'Web Development'), ('ai_ml', 'AI / ML'), ('cyber_security', 'Cyber Security'), ('cloud', 'Cloud Computing')], max_length=50, null=True),
        ),
    ]
