# Generated by Django 4.2 on 2026-03-23 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_add_aptitude_test_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroadmapprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_roadmap_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
