# Generated by Django 4.2 on 2026-03-23 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userroadmapprogress_user'),
        ('core', '0006_aptitude_only'),
    ]

    operations = [
    ]
