# Generated by Django 4.2 on 2026-03-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260324_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitudetestresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
