# Generated by Django

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aptitudetestresult_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-code', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Roadmap Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('estimated_hours', models.IntegerField(default=0)),
                ('resources', models.JSONField(blank=True, default=dict)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.roadmapcategory')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='_roadmapitem_prerequisites_+', symmetrical=False, to='core.roadmapitem')),
            ],
            options={
                'verbose_name_plural': 'Roadmap Items',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserRoadmapProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('roadmap_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.roadmapitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_roadmap_progress', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'User Roadmap Progress',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userroadmapprogress',
            unique_together={('user', 'roadmap_item')},
        ),
    ]
