# Generated by Django 4.2 on 2026-03-23 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_create_roadmap_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitudetestresult',
            name='time_taken',
            field=models.CharField(default='00:00:00', help_text='Time taken to complete the test', max_length=20),
        ),
        migrations.AlterField(
            model_name='roadmapitem',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='core.roadmapitem'),
        ),
        migrations.AlterField(
            model_name='userroadmapprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_roadmap_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
