# Generated by Django 4.2 on 2026-02-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_certification_course_project_alter_skill_skill_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalidentity',
            old_name='current_company',
            new_name='education_level',
        ),
        migrations.RenameField(
            model_name='professionalidentity',
            old_name='industry',
            new_name='native_language',
        ),
        migrations.RemoveField(
            model_name='professionalidentity',
            name='current_job_title',
        ),
        migrations.RemoveField(
            model_name='professionalidentity',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='professionalidentity',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalidentity',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='professionalidentity',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
