# Generated by Django 4.2 on 2026-03-23 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0004_alter_education_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoadmapProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_path', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('skill_name', models.CharField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('category_index', models.IntegerField(default=0)),
                ('skill_index', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['career_path', 'category_index', 'skill_index'],
                'unique_together': {('user', 'career_path', 'skill_name')},
            },
        ),
    ]
