# Generated by Django 4.2 on 2026-03-23 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0005_userroadmapprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('grade', models.CharField(max_length=20)),
                ('correct_answers', models.TextField()),
                ('incorrect_answers', models.TextField()),
                ('time_taken', models.IntegerField(blank=True, null=True)),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_test_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.AddIndex(
            model_name='technicaltestresult',
            index=models.Index(fields=['user', 'subject'], name='skills_tech_user_id_d9b6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='technicaltestresult',
            index=models.Index(fields=['user', 'test_date'], name='skills_tech_user_id_793665_idx'),
        ),
    ]
