# Generated by Django 4.2 on 2026-03-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('infosys', 'Infosys'), ('tcs', 'TCS'), ('coursera', 'Coursera'), ('nasscom', 'NASSCOM'), ('govt', 'Government'), ('other', 'Other')], max_length=20)),
                ('domain', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('registration_url', models.URLField(max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('duration', models.CharField(help_text='Duration of the certification', max_length=100)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
