# Generated by Django 4.2 on 2026-03-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('coursera', 'Coursera'), ('aws', 'AWS'), ('google', 'Google'), ('microsoft', 'Microsoft'), ('cisco', 'Cisco'), ('pmi', 'PMI'), ('scrum_alliance', 'Scrum Alliance'), ('adobe', 'Adobe'), ('tableau', 'Tableau'), ('oracle', 'Oracle')], max_length=50)),
                ('domain', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('registration_url', models.URLField()),
                ('rating', models.FloatField(default=4.0)),
                ('duration', models.CharField(max_length=100)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_synced', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
                'unique_together': {('name', 'provider')},
            },
        ),
    ]
