# Generated by Django 4.2 on 2026-03-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='partner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='certification',
            name='provider',
            field=models.CharField(choices=[('Coursera', 'Coursera'), ('AWS', 'AWS'), ('Google Cloud', 'Google Cloud'), ('Microsoft', 'Microsoft'), ('Cisco', 'Cisco'), ('PMI', 'PMI'), ('Scrum Alliance', 'Scrum Alliance'), ('Adobe', 'Adobe'), ('Tableau', 'Tableau'), ('Oracle', 'Oracle')], max_length=50),
        ),
        migrations.AlterField(
            model_name='certification',
            name='registration_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='certification',
            name='source',
            field=models.CharField(default='manual', max_length=100),
        ),
    ]
