# Generated by Django 4.2 on 2026-03-20 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='external_id',
            field=models.CharField(blank=True, help_text='External API ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='certification',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('csv_import', 'CSV Import'), ('microsoft_api', 'Microsoft API'), ('coursera_api', 'Coursera API'), ('linkedin_api', 'LinkedIn API'), ('aws_scraped', 'AWS Web Scraping'), ('google_scraped', 'Google Web Scraping'), ('other_api', 'Other API')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='provider',
            field=models.CharField(choices=[('aws', 'AWS'), ('google', 'Google Cloud'), ('microsoft', 'Microsoft'), ('coursera', 'Coursera'), ('linkedin', 'LinkedIn Learning'), ('edx', 'edX'), ('udacity', 'Udacity'), ('pluralsight', 'Pluralsight'), ('infosys', 'Infosys'), ('tcs', 'TCS'), ('nasscom', 'NASSCOM'), ('govt', 'Government'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['provider', 'is_active'], name='certificati_provide_bfa877_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['domain', 'is_active'], name='certificati_domain_362ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['source', 'last_updated'], name='certificati_source_50f703_idx'),
        ),
    ]
